[package]
name = "web-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
viewbuilder = { path = "../", features = ["full"] }
concoct = { git = "https://github.com/concoct-rs/concoct" }
