
[package]
name = "viewbuilder"
version = "0.9.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[workspace]
members = [
    ".",
    "web_examples/counter"
]

[features]
full = []

[dependencies]
tokio = { version = "1.35.1", features = ["full"], optional = true }
web-sys = { version = "0.3.66", features = ["Document", "HtmlElement", "Window", "Text"] }

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

