[package]
name = "viewbuilder"
version = "0.6.0-alpha.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/concoct-rs/viewbuilder"

[features]
gl = [
    "dep:gl",
    "dep:glutin",
    "dep:glutin-winit",
    "dep:raw-window-handle",
    "dep:winit",
    "dep:skia-safe",
]
layout = ["dep:taffy"]
semantics = ["dep:accesskit"]
element = ["dep:skia-safe"]
full = ["gl", "layout", "semantics", "element"]
default = []

[dependencies]
accesskit = { version = "0.11.2", optional = true }

kurbo = "0.9.5"
slotmap = "1.0.6"

taffy = { version = "0.3.13", optional = true }

gl = { version = "0.14.0", optional = true }
glutin = { version = "0.30.10", optional = true }
glutin-winit = { version = "0.3.0", optional = true }
raw-window-handle = { version = "0.5.2", optional = true }
skia-safe = { version = "0.66.2", features = ["gl"], optional = true }
winit = { version = "0.28.7", optional = true }
interpolation = "0.3.0"
tokio = { version = "1.32.0", features = ["full"] }
thiserror = "1.0.49"
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", features = ["dioxus"] }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus" }
shipyard = { version = "0.6.2", features = ["proc", "std"], default-features = false }
rustc-hash = "1.1.0"
quadtree_rs = "0.1.3"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "dom"
required-features = ["full"]
