[package]
name = "viewbuilder"
version = "0.9.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[features]
full = []

[dependencies]
anyhow = "1.0.79"
pollster = "0.3.0"
slotmap = "1.0.7"
tokio = { version = "1.35.1", features = ["full"] }
vello = { git = "https://github.com/linebender/vello" }
wgpu = { version = "0.18" }
winit = "0.28.1"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

