[package]
name = "viewbuilder"
version = "0.8.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[features]
EventLoop = ["dep:winit"]
Window = ["EventLoop"]
full = ["Window"]

[dependencies]
tokio = { version = "1.32.0", features = ["full"], optional = true }
winit = { version = "0.28.1", optional = true }
concoct = { path = "../concoct", features = ["full"] }

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "window"
required-features = ["Window"]
