[package]
name = "viewbuilder"
version = "0.10.0-alpha.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[workspace]
members = [
    ".",
    "web_examples/counter",
    "web_examples/todomvc"
]

[features]
web = ["web-sys"]
full = ["web", "tracing"]

[dependencies]
rustc-hash = "1.1.0"
tracing = { version = "0.1.40", optional = true }

[dependencies.web-sys]
version = "0.3.66"
optional = true
features = [
    "Document",
    "Event",
    "HtmlElement",
    "Window",
    "Text"
]

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

