[package]
name = "viewbuilder"
version = "0.6.0-alpha.3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/concoct-rs/viewbuilder"

[features]
gl = [
    "dep:gl",
    "dep:glutin",
    "dep:glutin-winit",
    "dep:raw-window-handle",
    "dep:winit",
    "dep:skia-safe",
]
layout = ["dep:taffy"]
semantics = ["dep:accesskit"]
element = ["dep:skia-safe"]
full = ["gl", "layout", "semantics", "element"]
default = ["full"]

[dependencies]
accesskit = { version = "0.11.2", optional = true }

kurbo = "0.9.5"
slotmap = "1.0.6"

taffy = { version = "0.3.13", optional = true }
gl = { version = "0.14.0", optional = true }
glutin = { version = "0.31", optional = true }
glutin-winit = { version = "0.4.2", optional = true }
raw-window-handle = { version = "0.5.2", optional = true }
skia-safe = { version = "0.66.2", features = ["gl"], optional = true }
winit = { version = "0.29.3", optional = true }
tokio = { version = "1.32.0", features = ["full"] }
rustc-hash = "1.1.0"
futures = "0.3.29"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "app"
required-features = ["full"]
