[package]
name = "viewbuilder"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/concoct-rs/viewbuilder"

[workspace]
members = [
    ".",
    "macros"
]

[features]
ui = ["winit"]
full = ["ui"]

[dependencies]
kurbo = "0.9.5"
tokio = { version = "1.32.0", features = ["full"] }
slotmap = "1.0.6"
winit = { version = "0.28.1", optional = true }
viewbuilder-macros = { path = "macros" }

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "app"
required-features = ["full"]
