[package]
name = "viewbuilder"
version = "0.9.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[features]
full = []

[dependencies]
concoct = { git = "https://github.com/concoct-rs/concoct" }
tokio = { version = "1.35.1", features = ["full"] }

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

