[package]
name = "viewbuilder"
version = "0.6.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/matthunz/viewbuilder"

[workspace]
members = [
    ".",
    "macros",
    "web-examples"
]

[features]
native = []
web = ["dep:web-sys"]
full = ["native", "web"]
web-sys = ["dep:web-sys"]

[dependencies]
kurbo = "0.9.5"
tokio = { version = "1.32.0", features = ["full"] }
slotmap = "1.0.7"
winit = { version = "0.28.1" }
concoct = { git = "https://github.com/concoct-rs/concoct" }
viewbuilder-macros = { path = "macros" }
web-sys = { version = "0.3.66", optional = true, features = ["Document", "HtmlElement", "Text", "Window"] }

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "app"
required-features = ["native"]
