[package]
name = "viewbuilder-macros"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macros for Viewbuilder"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.40", features = ["full"] }
